In [57]:
import numpy as np
import pandas as pd
from pathlib import Path
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
p = Path(r'E:/MSA/Fall 2023/Grad/MixedSet2.csv')

data = pd.read_csv(p)

In [58]:
X =  data.iloc[:, :-1].values
print(X)
y = data.iloc[:, -1].values
print(y)


[[0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]
['Lack of coolant'
 'The cooling system is clogged - it needs to be cleaned'
 'check the ventilation unit'
 'The alternator belt may be slipping or the

In [59]:
dimensionality_reduction = data.groupby(data['problem']).max()
print(dimensionality_reduction)


                                                    symptomA_Car exhaust smoke  \
problem                                                                          
A new head gasket may be needed                                              1   
Check for a vacuum leak or moisture in the dist...                           0   
Check if the air filter is clean. If so then ch...                           1   
Check the balance of the four wheels                                         0   
Lack of coolant                                                              0   
Matching problem between the brake pads and the...                           0   
The alternator belt may be slipping or the fan ...                           0   
The cooling system is clogged - it needs to be ...                           0   
The engine sensor may be damaged                                             1   
The engine sensor may be faulty                                              1   
This is a normal

In [60]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)
print(y)

[ 4  7 12  6  2  9  0 10 10  8  5  1  3  5 11  5]


In [61]:
model = tree.DecisionTreeClassifier()
model.fit(X,y)

DecisionTreeClassifier()

In [62]:
model


DecisionTreeClassifier()

In [63]:
cols     = data.columns
cols     = cols[:-1]

In [64]:
importances = model.feature_importances_
indices = np.argsort(importances)[::-1]
features = cols

In [65]:
from sklearn.tree import _tree

In [66]:
def execute_bot():

    print("Please reply with yes/Yes or no/No for the following symptoms") 
    def print_problem(node):
        #print(node)
        node = node[0]
        #print(len(node))
        val  = node.nonzero() 
        #print(val)
        problem = labelencoder.inverse_transform(val[0])
        return problem
    def tree_to_code(tree, feature_names):
        tree_ = tree.tree_
        #print(tree_)
        feature_name = [
            feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
            for i in tree_.feature
        ]
        symptoms_present = []
        def recurse(node, depth):
            indent = "  " * depth
            if tree_.feature[node] != _tree.TREE_UNDEFINED:
                name = feature_name[node]
                threshold = tree_.threshold[node]
                print(name + " ?")
                ans = input()
                ans = ans.lower()
                if ans == 'yes':
                    val = 1
                else:
                    val = 0
                if  val <= threshold:
                    recurse(tree_.children_left[node], depth + 1)
                else:
                    symptoms_present.append(name)
                    recurse(tree_.children_right[node], depth + 1)
            else:
                present_problem = print_problem(tree_.value[node])
                
                print('The Model Suggests:')
                print()
                print( "You may have: " +  present_problem )
                print()
                row = CarDiagnose[CarDiagnose['problem'] == present_problem[0]]
                print('Description: ', str(row['Description'].values))
                print()
                print('Inspection List: ', str(row['InspectionList'].values))
    
        recurse(0, 1)
    
    tree_to_code(model,cols)




In [67]:
D = Path(r'E:/MSA/Fall 2023/Grad/CarDiagnose.csv')

Isnpection_dataset = pd.read_csv(D, names = ['Description','InspectionList'])

problem = dimensionality_reduction.index
problem = pd.DataFrame(problem)

CarDiagnose = pd.DataFrame()

CarDiagnose['Description'] = np.nan
CarDiagnose['InspectionList'] = np.nan

CarDiagnose['problem'] = np.nan
CarDiagnose['problem'] = problem['problem']


CarDiagnose['Description'] = Isnpection_dataset['Description']
CarDiagnose['InspectionList'] = Isnpection_dataset['InspectionList']


In [68]:
execute_bot()

Please reply with yes/Yes or no/No for the following symptoms
symptomA_The car shakes ?
symptomB_white smoke ?
symptomB_black smoke ?
symptomC_The smoke comes out of the exhaust when starting and then stops ?
The Model Suggests:

['You may have: The engine sensor may be faulty']

Description:  ['Engine mounts are subject to normal wear; however, excessive torque and movement between the engine block and frame can prematurely weaken them. If one engine mount is bad, it is common for the other to be worn. Replacing both at the same time is strongly recommended.']

Inspection List:  ["1) Start the engine and locate the engine mounts. 2) Have an assistant in the vehicle, apply the parking brake, press the brake pedal with your left foot, shift the transmission into gear and lightly apply pressure onto the gas pedal. 3) When torque is applied to the engine while in gear, visually inspect the engine mounts. Look for excessive movement in the engine mounts and listen for a knocking noise when